sudo: required
services:
  - docker

before_install:
  - docker build -t mykeET/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run mykeET/react-test npm test -- --coverage

  after_success:
    - docker build -t mykeET/multi-client ./client
    - docker build -t mykeET/multi-nginx ./multi-nginx
    - docker build -t mykeET/multi-server ./multi-server
    - docker build -t mykeET/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push mykeET/multi-client
    - docker push mykeET/multi-nginx
    - docker push mykeET/multi-server
    - docker push mykeET/multi-worker

